# Generated by Django 4.2.6 on 2023-10-27 12:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(max_length=100)),
                ('planDescription', models.CharField(max_length=100)),
                ('planAmount', models.FloatField()),
                ('planDiscountName', models.CharField(blank=True, max_length=100)),
                ('planDiscountPercentage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('imageUrl', models.URLField(blank=True)),
                ('specialBenfit', models.BooleanField(default=False)),
                ('iconName', models.CharField(blank=True, max_length=100)),
                ('fullDetails', tinymce.models.HTMLField(blank=True)),
                ('selectedPlan', models.ManyToManyField(related_name='selectedPlan', to='cricbuzzApp.subscriptionplantable')),
            ],
        ),
    ]
